AM1007/foodies-app

frontend/package-lock.json
frontend/package.json
frontend/src/main.jsx
frontend/src/pages/Home/Home.jsx
frontend/src/pages/NotFound/NotFound.jsx
frontend/src/pages/Profile/Profile.jsx
frontend/src/pages/Recipe/Recipe.jsx

fix(files) delete helmet

---

frontend/vercel.json

feat(json): change vercei config

---

backend/controllers/authControllers.js
backend/db/models/Area.js
backend/db/models/User.js
backend/decorators/ctrlWrapper.js
backend/decorators/validateBody.js
backend/helpers/HttpError.js
backend/package.json
backend/routes/authRouter.js
backend/schemas/authSchemas.js
backend/scripts/seedAreas.js
backend/scripts/seedCategories.js
backend/scripts/seedIngredients.js
backend/scripts/seedUsers.js
backend/services/authServices.js

add: db migration scripts

---

frontend/src/components/Logo/Logo.jsx

logo update

---

frontend/src/pages/Recipe/Recipe.jsx

create structure for Recipe add page

---

backend/app.js
backend/controllers/areasControllers.js
backend/controllers/categoriesControllers.js
backend/controllers/ingredientsControllers.js
backend/controllers/testimonialControllers.js
backend/db/models/Category.js
backend/db/models/Testimonial.js
backend/decorators/ctrlWrapper.js
backend/decorators/validateBody.js
backend/routes/areasRouter.js
backend/routes/categoriesRouter.js
backend/routes/ingredientsRouter.js
backend/routes/testimonialRouter.js
backend/services/areasServices.js
backend/services/categoriesServices.js
backend/services/ingredientsServices.js
backend/services/testimonialServices.js
backend/todelete/testimonials.json

introduced endpoints for categories, areas, ingredients and testimonials

---

backend/app.js
backend/controllers/authControllers.js
backend/decorators/validateBody.js
backend/helpers/jwt.js
backend/middlewares/authenticate.js
backend/package-lock.json
backend/routes/authRouter.js
backend/schemas/authSchemas.js
backend/scripts/seedTestimonials.js
backend/services/authServices.js
backend/services/usersServices.js

added login/logout endpoints, authenticate middleware

---

backend/db/models/Category.js
backend/db/models/RecipeIngredient.js

fix: recipeIngredient model

---

frontend/src/App.jsx
package-lock.json

fix(jsx & json): del link & file

---

backend/controllers/recipesControllers.js
backend/decorators/validateQuery.js
backend/routes/recipesRouter.js
backend/services/recipesServices.js

add recipe endpoints

---

frontend/package-lock.json
frontend/package.json
frontend/src/redux/areas/areasSlice.js
frontend/src/redux/categories/categoriesSlice.js
frontend/src/redux/ingredients/ingredientsSlice.js
frontend/src/redux/recipes/recipesSlice.js
frontend/src/redux/redux.md
frontend/src/redux/store.js
frontend/src/redux/testimonials/testimonialsSlice.js
frontend/src/redux/users/authSlice.js
frontend/src/redux/users/userSlice.js

feat(redux): add slices and store setup

---

frontend/package-lock.json
frontend/src/App.jsx
frontend/src/components/PrivateRoute.jsx

feat(routes): added private routes for recipe and profile pages

---

frontend/src/components/NetworkLinks/NetworkLinks.module.css
frontend/src/components/sections/Footer/Footer.jsx
frontend/src/components/sections/Footer/Footer.module.css
frontend/src/components/sections/Hero/Hero.jsx
frontend/src/index.css
frontend/src/pages/Home/Home.jsx

footer styles adjastment

---

frontend/src/components/RecipePage/PopularRecipes.jsx
frontend/src/components/RecipePage/PopularRecipes.module.css
frontend/src/components/RecipePage/RecipeInfo.jsx
frontend/src/components/RecipePage/RecipeInfo/RecipeIngredients.jsx
frontend/src/components/RecipePage/RecipeInfo/RecipeIngredients.module.css
frontend/src/components/RecipePage/RecipeInfo/RecipeMainInfo.jsx
frontend/src/components/RecipePage/RecipeInfo/RecipeMainInfo.module.css
frontend/src/components/RecipePage/RecipeInfo/RecipePreparation.jsx
frontend/src/components/RecipePage/RecipeInfo/RecipePreparation.module.css
frontend/src/components/RecipePreview/RecipeCard.jsx
frontend/src/components/RecipePreview/RecipeCard.module.css

add:components recipePage

---

frontend/src/components/RecipePage/PopularRecipes.jsx
frontend/src/components/RecipePage/RecipeInfo.jsx
frontend/src/components/RecipePage/RecipeInfo/RecipeMainInfo.module.css
frontend/src/components/RecipePage/RecipeInfo/RecipePreparation.jsx
frontend/src/components/ui/PathInfo/PathInfo.jsx
frontend/src/components/ui/PathInfo/PathInfo.module.css
frontend/src/pages/Recipe/Recipe.jsx
frontend/src/pages/Recipe/Recipe.module.css

add:page recipePage

---

frontend/src/pages/AddRecipe/AddRecipe.jsx
frontend/src/pages/AddRecipe/AddRecipe.module.css

createmRecipe add page

---

backend/constants/auth.js
backend/constants/httpStatus.js
backend/controllers/authControllers.js
backend/controllers/recipesControllers.js
backend/controllers/usersControllers.js
backend/helpers/HttpError.js
backend/routes/recipesRouter.js
backend/services/authServices.js
backend/services/recipesServices.js

fix: add constants HTTP_STATUS into separate file httpStatus.js

---

frontend/src/App.jsx

add: route to AddRecipePage

---

frontend/src/components/sections/Hero/Hero.jsx
frontend/src/components/sections/Hero/Hero.module.css
frontend/src/components/sharedTitle/SubTitle/Subtitle.module.css
frontend/src/pages/Home/Home.jsx

create section hero

---

frontend/src/components/Layout/Layout.jsx
frontend/src/components/Logo/Logo.jsx
frontend/src/components/Navigation/Navigation.jsx
frontend/src/components/Navigation/Navigation.module.css
frontend/src/components/sections/Header/Header.jsx
frontend/src/components/sections/Header/Header.module.css

fix(logo, header): implement dynamic color change for Logo and move Header component

---

frontend/src/api/api.js
frontend/src/redux/areas/areasSlice.js
frontend/src/redux/categories/categoriesSlice.js
frontend/src/redux/ingredients/ingredientsSlice.js
frontend/src/redux/recipes/recipesSlice.js
frontend/src/redux/testimonials/testimonialsSlice.js
frontend/src/redux/users/authSlice.js
frontend/src/redux/users/userSlice.js

feat(api): centralize axios baseURL config in api.js and update slices

---

frontend/src/components/Header/Header.jsx
frontend/src/components/Layout/Layout.jsx
frontend/src/context/ModalContext.js
frontend/src/context/ModalContext.jsx
frontend/src/hooks/useModal.js
frontend/src/main.jsx
frontend/src/pages/Profile/Profile.jsx

added useModal hook

---

frontend/src/App.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/MainTitle/MainTitle.jsx
frontend/src/components/MainTitle/MainTitle.module.css
frontend/src/components/Navigation/Navigation.jsx
frontend/src/components/Subtitle/Subtitle.jsx
frontend/src/components/Subtitle/Subtitle.module.css
frontend/src/pages/AddRecipe/AddRecipePage.jsx

add: MainTitle, Subtitle, AddRecipeForm components

---

frontend/src/components/MobileMenu/MobileMenu.jsx
frontend/src/components/MobileMenu/MobileMenu.module.css
frontend/src/components/ui/BurgerBtn/BurgerBtn.module.css
frontend/src/hooks/useScrollLock.js

fixed mobile menu

---

frontend/src/App.jsx
frontend/src/components/ui/MainTitle/MainTitle.jsx
frontend/src/components/ui/MainTitle/MainTitle.module.css
frontend/src/components/ui/PathInfo/PathInfo.jsx
frontend/src/components/ui/PathInfo/PathInfo.module.css
frontend/src/components/ui/Subtitle/Subtitle.module.css
frontend/src/index.css
frontend/src/pages/Profile/Profile.jsx

feat(files): add components to page & styles

---

backend/backend.txt
backend/constants/auth.js
backend/docs/components/recipes/RecipeDetail.yaml
backend/docs/components/schemas/areas/Area.yaml
backend/docs/components/schemas/categories/Category.yaml
backend/docs/components/schemas/ingredients/Ingredient.yaml
backend/docs/components/schemas/recipes/CreateRecipeRequest.yaml
backend/docs/components/schemas/recipes/Pagination.yaml
backend/docs/components/schemas/recipes/RecipePreview.yaml
backend/docs/components/schemas/testimonials/Testimonial.yaml
backend/docs/openapi.yaml
backend/docs/paths/areas/getAreas.yaml
backend/docs/paths/categories/getCategories.yaml
backend/docs/paths/ingredients/getIngredients.yaml
backend/docs/paths/recepies/addToFavorites.yaml
backend/docs/paths/recepies/createRecipe.yaml
backend/docs/paths/recepies/deleteRecipe.yaml
backend/docs/paths/recepies/getFavoriteRecipes.yaml
backend/docs/paths/recepies/getPopularRecipes.yaml
backend/docs/paths/recepies/getRecipeById.yaml
backend/docs/paths/recepies/getUserRecipes.yaml
backend/docs/paths/recepies/removeFromFavorites.yaml
backend/docs/paths/recepies/searchRecipes.yaml
backend/docs/paths/testimonials/getTestimonials.yaml
backend/routes/recipesRouter.js
backend/services/authServices.js
backend/services/recipesServices.js

fix: some routes & swagger added

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/SelectCategory/SelectCategory.jsx
frontend/src/components/SelectCategory/SelectCategory.module.css
frontend/src/components/ui/TimeController/TimeController.jsx
frontend/src/components/ui/TimeController/TimeController.module.css

add component time controller

---

backend/API_DOCUMENTATION.md
backend/swaggerConfig.js

add: remote swagger link

---

frontend/src/App.jsx
frontend/src/components/sections/Categories/Categories.jsx
frontend/src/components/sections/Testimonials/Testimonials.jsx
frontend/src/components/ui/MainTitle/MainTitle.jsx
frontend/src/components/ui/Subtitle/Subtitle.jsx
frontend/src/data/testimonials.js
frontend/src/pages/AddRecipe/AddRecipePage.jsx
frontend/src/pages/Profile/Profile.jsx

fix(files) change variable

---

frontend/src/components/sections/Hero/Hero.jsx
frontend/src/components/sections/Hero/Hero.module.css

add path to the button

---

frontend/src/components/SignUpForm/SignUpForm.jsx
frontend/src/main.jsx
frontend/src/redux/store.js
frontend/src/redux/users/operations.js

adding more logic for modals

---

frontend/src/components/sections/Footer/Footer.jsx

adding current year in footer

---

.github/CODEOWNERS
frontend/src/api/api.js

feat(js): update api

---

frontend/src/redux/users/authSlice.js

feat(js): update auth slice

---

frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/LogOutModal/LogOutModal.module.css
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignInModal/SignInModal.jsx
frontend/src/components/SignInModal/SignInModal.module.css
frontend/src/components/SignUpModal/SignUpModal.jsx
frontend/src/components/SignUpModal/SignUpModal.module.css

updated logic for modals

---

frontend/src/components/Layout/Layout.jsx

Fixed Layout

---

frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/SignInForm/SignInForm.jsx

update login and logout logic

---

frontend/src/api/api.js
frontend/src/components/Button/Button.jsx
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/main.jsx

Button type fix, added logs

---

backend/routes/authRouter.js

fix: delete cors options from authRouter

---

backend/app.js

fix: add Access-Control-Allow-Headers to cors options

---

backend/API_DOCUMENTATION.md
backend/README.md
backend/controllers/authControllers.js
backend/services/authServices.js
backend/swagger/schemas/area.js
backend/swagger/schemas/category.js
backend/swagger/schemas/ingredient.js
backend/swagger/schemas/user.js

add: user_reg_functions

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignUpForm/SignUpForm.jsx
frontend/src/components/sections/Footer/Footer.module.css

adding notification izitoast

---

backend/app.js
backend/backend.txt
backend/controllers/authControllers.js
backend/db/associations.js
backend/db/models/Favorite.js
backend/db/sequelize.js
backend/helpers/paginationHelper.js
backend/middlewares/upload.js
backend/routes/recipesRouter.js
backend/schemas/recipeSchemas.js
backend/scripts/seedAreas.js
backend/scripts/seedCategories.js
backend/scripts/seedIngredients.js
backend/scripts/seedRecipes.js
backend/scripts/seedTestimonials.js
backend/scripts/seedUsers.js
backend/services/authServices.js
backend/services/recipesServices.js
backend/swagger/definitions/areas.js
backend/swagger/definitions/auth.js
backend/swagger/definitions/categories.js
backend/swagger/definitions/ingredients.js
backend/swagger/definitions/recipes.js
backend/swagger/definitions/testimonials.js
backend/swagger/definitions/users.js
backend/swagger/schemas/testimonial.js

Recipe part

---

backend/db/sequelize.js

add: server raise

---

backend/db/sequelize.js

fix: sequilize

---

frontend/src/components/sections/Categories/Categories.jsx

fix(jsx): change import

---

backend/db/sequelize.js

fix: sequlize timouts

---

backend/db/sequelize.js

fix: render - db connection

---

backend/db/sequelize.js

fix: connection

---

backend/app.js
backend/db/sequelize.js

fix: sequlize settings

---

backend/db/sequelize.js

fix: db connection

---

backend/app.js
backend/db/sequelize.js

fix: improve db connection

---

backend/db/sequelize.js

fix: db deploy

---

frontend/src/components/CategoryList/CategoryList.jsx

fix(jsx): update icon import

---

frontend/src/components/ListItems/ListItems.jsx
frontend/src/components/ListItems/ListItems.module.css
frontend/src/pages/Profile/Profile.jsx

Add ListItems component with tab navigation and recipe deletion logic

---

frontend/package-lock.json
frontend/package.json

feat(json): add npm i react-hook-form package

---

frontend/package-lock.json
frontend/package.json

feat(jsx): add packages

---

backend/app.js
backend/db/sequelize.js

fix: sequalize rollback

---

backend/db/sequelize.js

fix: sequalize

---

frontend/src/components/RecipeList/RecipeList.jsx

feat(files): add recipe list

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx
frontend/src/components/PopularRecipes/PopularRecipes.module.css
frontend/src/components/RecipeInfo/RecipeInfo.jsx
frontend/src/components/RecipeInfo/RecipeInfo.module.css
frontend/src/components/RecipeIngredients/RecipeIngredients.jsx
frontend/src/components/RecipeIngredients/RecipeIngredients.module.css
frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/RecipeMainInfo/RecipeMainInfo.module.css
frontend/src/components/RecipePreparation/RecipePreparation.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.jsx
frontend/src/pages/Recipe/Recipe.jsx

fix:imports adn adding styles

---

backend/app.js

fix: cors paths

---

frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/RecipePreparation/RecipePreparation.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.module.css
frontend/src/pages/Recipe/Recipe.jsx

fix: fetching

---

frontend/src/pages/Recipe/Recipe.jsx

fix: uncomment recipepage prod

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx
frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.jsx

fix: recipeCard UI and resolve merge conflict

---

backend/controllers/recipesControllers.js
backend/db/sequelize.js
backend/routes/recipesRouter.js
backend/services/recipesServices.js

fix: console.log & error removed

---

backend/app.js

fix: cors path

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx

fix: popular ricipe empty list message

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx
frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx
frontend/src/components/RecipeInfo/RecipeInfo.jsx
frontend/src/components/RecipeIngredients/RecipeIngredients.jsx
frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.jsx
frontend/src/pages/Recipe/Recipe.jsx

fix: uploading images

---

frontend/src/components/ListItems/ListItems.jsx
frontend/src/components/ListItems/ListItems.module.css
frontend/src/data/emptyMessages.js

reorganize empty messages and enhance ListItems component logic

---

frontend/package-lock.json
frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/UserBar/UserBar.jsx

adding logout to userBar

---

frontend/package-lock.json
frontend/src/App.jsx
frontend/src/components/UserInfo/UserInfo.jsx
frontend/src/components/ui/UserAvatar/UserAvatar.jsx
frontend/src/pages/Profile/Profile.jsx
frontend/src/redux/users/userSlice.js

Profile update

---

frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/LogOutModal/LogOutModal.module.css

adding styles to logout modal

---

frontend/src/components/Button/Button.jsx
frontend/src/components/Layout/Layout.jsx
frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/SignUpForm/SignUpForm.jsx

adjusting toast

---

frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.module.css

fix: recipicard buttons heart and arrow

---

frontend/src/components/RecipeList/RecipeList.module.css

fix(css): change styles

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/IngredientSelector/IngredientSelector.jsx
frontend/src/components/IngredientSelector/IngredientSelector.module.css
frontend/src/components/TextAreaWithCount/TextAreaWithCount.jsx
frontend/src/components/TextAreaWithCount/TextAreaWithCount.module.css
frontend/src/components/UploadPecipePhoto/UploadRecipePhoto.jsx
frontend/src/components/UploadPecipePhoto/UploadRecipePhoto.module.css
frontend/src/components/ui/DropdownSelector/DropdownSelector.jsx
frontend/src/components/ui/DropdownSelector/DropdownSelector.module.css
frontend/src/components/ui/TimeController/TimeController.jsx
frontend/src/components/ui/TimeController/TimeController.module.css

Dev tetiana add recipe imports

---

frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignUpForm/SignUpForm.jsx
frontend/src/components/SignUpForm/SignUpForm.module.css

styles adjustments for sign in and sign up forms

---

frontend/src/components/RecipeFilters/RecipeFilters.jsx
frontend/src/components/RecipeFilters/RecipeFilters.module.css
frontend/src/components/ui/DropdownSelector/DropdownSelector.module.css

add: Recipe Filters component

---

frontend/src/components/CategoryList/CategoryList.jsx
frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx
frontend/src/components/RecipeList/RecipeList.jsx
frontend/src/components/RecipeList/RecipeList.module.css
frontend/src/components/sections/Categories/Categories.jsx
frontend/src/components/sections/Categories/Categories.module.css
frontend/src/pages/Home/Home.jsx
frontend/src/redux/recipes/recipesSlice.js

feat(files): add routing to recipe list

---

frontend/src/App.jsx
frontend/src/components/Layout/Layout.jsx
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/UserBar/UserBar.jsx
frontend/src/components/ui/UserAvatar/UserAvatar.jsx
frontend/src/context/UserContext.jsx
frontend/src/pages/Home/Home.jsx

User context added

---

frontend/src/components/UserBar/UserBar.module.css
frontend/src/components/UserInfo/UserInfo.jsx
frontend/src/components/UserInfo/UserInfo.module.css
frontend/src/components/ui/UserAvatar/UserAvatar.jsx
frontend/src/components/ui/UserAvatar/UserAvatar.module.css
frontend/src/pages/Profile/Profile.jsx
frontend/src/pages/Profile/Profile.module.css

styles fixes for user info

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx
frontend/src/components/PopularRecipes/PopularRecipes.module.css
frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx
frontend/src/components/RecipeInfo/RecipeInfo.jsx
frontend/src/components/RecipeInfo/RecipeInfo.module.css
frontend/src/components/RecipeIngredients/RecipeIngredients.jsx
frontend/src/components/RecipeIngredients/RecipeIngredients.module.css
frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/RecipeMainInfo/RecipeMainInfo.module.css
frontend/src/components/RecipePreparation/RecipePreparation.jsx
frontend/src/components/RecipePreparation/RecipePreparation.module.css

fix: styles and _id vs id

---

frontend/src/components/UserBar/UserBar.jsx
frontend/src/components/sections/Header/Header.jsx

fixed UserBar

---

frontend/src/components/RecipeFilters/RecipeFilters.jsx
frontend/src/components/RecipeFilters/RecipeFilters.module.css
frontend/src/components/RecipeList/RecipeList.jsx
frontend/src/components/RecipeList/RecipeList.module.css
frontend/src/components/sections/Categories/Categories.module.css
frontend/src/components/ui/RecipeCard/RecipeCard.module.css

feat(files): add styles

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/RecipeIngredients/RecipeIngredients.jsx
frontend/src/components/RecipeIngredients/RecipeIngredients.module.css

add: remove btn

---

frontend/src/App.jsx
frontend/src/components/Button/Button.jsx
frontend/src/components/Button/Button.module.css
frontend/src/components/Button/DoubledButton.jsx
frontend/src/components/Button/buttonVariants.module.css
frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/LogOutModal/LogOutModal.module.css
frontend/src/components/Modal/Modal.module.css
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignUpForm/SignUpForm.jsx
frontend/src/components/SignUpForm/SignUpForm.module.css
frontend/src/components/SignUpModal/SignUpModal.module.css

added variants to button logic, style fixes

---

frontend/src/components/PopularRecipes/PopularRecipes.module.css
frontend/src/components/ui/RecipeCard/RecipeCard.module.css

Update style in components RecipeCard and PopularRecipe

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/TextAreaWithCount/TextAreaWithCount.module.css
frontend/src/components/UploadPecipePhoto/UploadRecipePhoto.jsx
frontend/src/components/UploadPecipePhoto/UploadRecipePhoto.module.css
frontend/src/components/ui/RecipeTitleInput/RecipeTitleInput.jsx
frontend/src/components/ui/RecipeTitleInput/RecipeTitleInput.module.css
frontend/src/pages/AddRecipe/AddRecipePage.jsx

Dev tetiana style

---

frontend/src/components/UserBar/UserBar.jsx
frontend/src/components/UserBar/UserBar.module.css
frontend/src/components/ui/UserAvatar/UserAvatar.jsx

fixed Avatar in header

---

backend/services/usersServices.js

added recipes to the user response

---

backend/services/usersServices.js

added instructions to recipes by user

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx
frontend/src/components/RecipeInfo/RecipeInfo.module.css
frontend/src/components/RecipeIngredients/RecipeIngredients.jsx
frontend/src/components/RecipeIngredients/RecipeIngredients.module.css
frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/RecipeMainInfo/RecipeMainInfo.module.css
frontend/src/components/RecipePreparation/RecipePreparation.jsx
frontend/src/components/RecipePreparation/RecipePreparation.module.css
frontend/src/components/ui/RecipeCard/RecipeCard.module.css
frontend/src/pages/Recipe/Recipe.jsx
frontend/src/pages/Recipe/Recipe.module.css

Update: styles

---

frontend/src/components/ui/RecipeCard/RecipeCard.module.css

Update: styles in RecipeCard

---

frontend/src/App.jsx

update(jsx): change routes

---

frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/LogOutModal/LogOutModal.module.css
frontend/src/components/Modal/Modal.module.css
frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignInModal/SignInModal.jsx
frontend/src/components/SignInModal/SignInModal.module.css
frontend/src/components/SignUpForm/SignUpForm.module.css
frontend/src/components/SignUpModal/SignUpModal.jsx
frontend/src/components/SignUpModal/SignUpModal.module.css

modals sizing

---

frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx

fix(jsx): change routes

---

frontend/src/components/ui/RecipeCard/RecipeCard.module.css

feat(css): add styles

---

frontend/src/components/Navigation/Navigation.jsx
frontend/src/components/sections/Hero/Hero.jsx

fix(jsx): add route

---

frontend/src/components/RecipeFilters/RecipeFilters.jsx
frontend/src/components/RecipeList/RecipeList.jsx
frontend/src/components/RecipePagination/RecipePagination.jsx
frontend/src/components/RecipePagination/RecipePagination.module.css

feat(files): add pagination

---

frontend/frontend.txt
frontend/src/components/CategoryCard/CategoryCard.jsx
frontend/src/components/CategoryCard/CategoryCard.module.css
frontend/src/components/CategoryList/CategoryList.jsx
frontend/src/components/CategoryList/CategoryList.module.css
frontend/src/components/sections/Categories/Categories.jsx

add: CategoryCard component

---

frontend/src/components/RecipeList/RecipeList.jsx

fix: recipeLict filter destroyed

---

frontend/src/components/RecipeList/RecipeList.jsx

Reverts AM1007/foodies-app#214

Revert "fix: recipeLict filter destroyed"

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/IngredientSelector/IngredientSelector.jsx
frontend/src/components/IngredientSelector/IngredientSelector.module.css
frontend/src/components/TextAreaWithCount/TextAreaWithCount.module.css
frontend/src/components/ui/TimeController/TimeController.jsx
frontend/src/components/ui/TimeController/TimeController.module.css

fix: style of component

---

frontend/src/components/sections/Testimonials/Testimonials.jsx
frontend/src/redux/testimonials/testimonialsSlice.js

feat(jsx & js): add use memo

---

frontend/src/components/AuthBar/AuthBar.jsx
frontend/src/components/AuthBar/AuthBar.module.css
frontend/src/components/DoubledButton/DoubledButton.jsx
frontend/src/components/MobileMenu/MobileMenu.jsx
frontend/src/components/MobileMenu/MobileMenu.module.css
frontend/src/components/Navigation/Navigation.jsx
frontend/src/components/Navigation/Navigation.module.css
frontend/src/components/UserBar/UserBar.jsx
frontend/src/components/UserBar/UserBar.module.css
frontend/src/components/sections/Header/Header.jsx
frontend/src/components/sections/Header/Header.module.css
frontend/src/components/sections/Hero/Hero.jsx
frontend/src/components/sections/Hero/Hero.module.css
frontend/src/components/ui/BurgerBtn/BurgerBtn.module.css
frontend/src/components/ui/CloseBtn/CloseBtn.module.css

fixed header

---

frontend/src/components/Navigation/Navigation.jsx
frontend/src/components/sections/Header/Header.jsx

fixed navigation

---

frontend/src/components/CategoryList/CategoryList.module.css
frontend/src/components/sections/Categories/Categories.module.css

small fix alignment

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/Layout/Layout.jsx
frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/main.jsx

toastify clean up

---

frontend/src/pages/NotFound/NotFound.module.css

not found image size

---

frontend/src/components/sections/Categories/Categories.module.css
frontend/src/icons/sprite.svg

feat(css & svg): add icon back

---

frontend/src/components/CategoryList/CategoryList.jsx
frontend/src/components/sections/Categories/Categories.jsx
frontend/src/redux/categories/categoriesSlice.js

fix: Categories Raised!

---

frontend/src/components/sections/Categories/Categories.module.css
frontend/src/icons/sprite.svg

feat(files): add styles & svg

---

frontend/src/api/api.js

fix: render path

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/IngredientSelector/IngredientSelector.jsx
frontend/src/components/IngredientSelector/IngredientSelector.module.css
frontend/src/components/TextAreaWithCount/TextAreaWithCount.module.css
frontend/src/components/UploadPecipePhoto/UploadRecipePhoto.module.css
frontend/src/components/ui/DropdownSelector/DropdownSelector.module.css
frontend/src/components/ui/PathInfo/PathInfo.module.css
frontend/src/components/ui/RecipeTitleInput/RecipeTitleInput.module.css
frontend/src/components/ui/TimeController/TimeController.jsx
frontend/src/components/ui/TimeController/TimeController.module.css
frontend/src/icons/sprite.svg

Dev tetiana error fix

---

frontend/src/components/sections/Categories/Categories.jsx
frontend/src/components/sections/Categories/Categories.module.css

feat(css & jsx): add styles

---

frontend/src/App.jsx
frontend/src/main.jsx

add: Chef avatar

---

frontend/src/components/CategoryList/CategoryList.module.css
frontend/src/components/Modal/Modal.module.css

adding hover changes

---

frontend/src/components/RecipeList/RecipeList.jsx
frontend/src/components/RecipeList/RecipeList.module.css

fix(css & jsx): add markup & styles

---

frontend/src/components/RecipeInfo/RecipeInfo.jsx
frontend/src/components/RecipePreparation/RecipePreparation.jsx
frontend/src/components/RecipePreview/RecipePreview.jsx
frontend/src/components/RecipePreview/RecipePreview.module.css
frontend/src/pages/Recipe/Recipe.jsx
frontend/src/redux/recipes/recipesSlice.js

opening recipe from profile

---

frontend/src/components/ui/RecipeCard/RecipeCard.module.css

fix(css): update styles

---

frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignInModal/SignInModal.module.css
frontend/src/components/SignUpForm/SignUpForm.jsx
frontend/src/components/SignUpForm/SignUpForm.module.css

added styles for validation error in forms

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx
frontend/src/components/PopularRecipes/PopularRecipes.module.css
frontend/src/components/RecipeIngredients/RecipeIngredients.jsx
frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/RecipePreparation/RecipePreparation.jsx
frontend/src/components/RecipePreparation/RecipePreparation.module.css

Update: styles removing additional container

---

frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignUpForm/SignUpForm.module.css

fixed error border

---

frontend/src/components/RecipePreparation/RecipePreparation.jsx
frontend/src/components/RecipePreparation/RecipePreparation.module.css

fix: add to favorite button

---

frontend/src/components/sections/Hero/Hero.jsx

feat: open modal on Add Recipe click if user is not authenticated

---

frontend/src/components/ListItems/ListItems.jsx
frontend/src/pages/Profile/Profile.jsx
frontend/src/redux/users/userSlice.js

fix for follow-unfollow

---

frontend/src/components/Loader/Loader.jsx
frontend/src/components/Loader/Loader.module.css

feat(files): add loader

---

frontend/src/components/Layout/Layout.jsx
frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/SignUpForm/SignUpForm.jsx

adding toast sign in, sign up slog out

---

frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx

fix: recipecard heart button

---

frontend/src/components/NetworkLinks/NetworkLinks.module.css

adding hover to socials

---

frontend/src/components/CategoryList/CategoryList.module.css

categories cards adjustments

---

README.md
commit_report_by_email.csv
frontend/package-lock.json
frontend/package.json
frontend/src/api/api.js
frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/IngredientSelector/IngredientSelector.jsx
frontend/src/components/IngredientSelector/IngredientSelector.module.css
frontend/src/components/LogOutModal/LogOutModal.jsx
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/redux/recipes/recipesSlice.js
frontend/src/redux/users/authSlice.js
frontend/vite.config.js
generate_commit_report.sh

fix: recipe upload

---

frontend/src/components/PopularRecipes/PopularRecipes.jsx
frontend/src/components/PopularRecipes/PopularRecipes.module.css
frontend/src/components/RecipeInfo/RecipeInfo.module.css
frontend/src/pages/Recipe/Recipe.jsx
frontend/src/pages/Recipe/Recipe.module.css

update: styles on recipe page mobile

---

frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/ui/TimeController/TimeController.module.css
frontend/src/pages/AddRecipe/AddRecipePage.jsx
frontend/src/pages/AddRecipe/AddRecipePage.module.css

update: styles on addrecipe page

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css

add: success notification and safe on refresh

---

backend/services/authServices.js

fixed trying to assign id to response if user is not found

---

frontend/src/components/CategoryList/CategoryList.jsx
frontend/src/components/SignInForm/SignInForm.jsx
frontend/src/components/SignInForm/SignInForm.module.css
frontend/src/components/SignUpForm/SignUpForm.jsx
frontend/src/components/SignUpForm/SignUpForm.module.css

adjusting styles for errors in modals

---

backend/constants/auth.js
backend/services/authServices.js

added validation for user name on sigh up

---

frontend/src/components/ui/ArrowBtn/ArrowBtn.jsx
frontend/src/components/ui/DeleteBtn/DeleteBtn.jsx
frontend/src/components/ui/DeleteBtn/DeleteBtn.module.css
frontend/src/components/ui/UploadAvatar/UploadAvatar.jsx
frontend/src/components/ui/UploadAvatar/UploadAvatar.module.css
frontend/src/components/ui/UserAvatar/UserAvatar.jsx

fix for avatar upload

---

frontend/src/components/RecipeMainInfo/RecipeMainInfo.jsx
frontend/src/components/UserBar/UserBar.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.jsx

Dropdown behaviour + links

---

frontend/src/api/api.js
frontend/src/components/Modal/Modal.module.css
frontend/src/components/SignInForm/SignInForm.jsx

fix issue with closing modal on error and incorrect redirection on login

---

frontend/src/components/Navigation/Navigation.jsx
frontend/src/components/Navigation/Navigation.module.css

fix: btn hover

---

frontend/src/components/ListItems/ListItems.jsx
frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx
frontend/src/components/RecipeFilters/RecipeFilters.jsx
frontend/src/components/RecipeList/RecipeList.jsx
frontend/src/components/RecipePreview/RecipePreview.module.css
frontend/src/components/UserPreview/UserPreview.module.css
frontend/src/components/ui/RecipeCard/RecipeCard.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.module.css
frontend/src/data/emptyMessages.js
frontend/src/pages/Profile/Profile.jsx
frontend/src/redux/recipes/recipesSlice.js

fixed rendering of recipes when adding to favorites

---

frontend/src/components/SignInForm/SignInForm.jsx

fix error message

---

frontend/index.html

Updated index.html for better SEO

---

frontend/src/redux/recipes/recipesSlice.js

fix: auto-remove deleted recipes from favorites

---

backend/middlewares/upload.js
backend/routes/recipesRouter.js
backend/routes/usersRouter.js
backend/services/cloudinary.js
frontend/src/components/AddRecipeForm/AddRecipeForm.jsx

add recipe image transformations for thumb and previews

---

frontend/src/redux/recipes/recipesSlice.js

fix: add error state reset

---

frontend/index.html
frontend/src/components/Loader/Loader.jsx
frontend/src/components/Loader/Loader.module.css
frontend/src/index.css
frontend/src/pages/NotFound/NotFound.jsx
package-lock.json

fix(files): update loader

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/components/ScrollToTop/ScrollToTop.jsx
frontend/src/components/ScrollToTop/ScrollToTop.module.css

feat(jsx): add scroll to top button

---

frontend/src/components/ScrollToTop/ScrollToTop.module.css

fix(css): add important to button

---

frontend/eslint.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/CircularText/CircularText.jsx
frontend/src/components/CircularText/CircularText.module.css
frontend/src/components/sections/Footer/Footer.jsx

feat(files): add button to modal

---

frontend/src/api/auth.js
frontend/src/redux/users/authSlice.js

fix issue refresh tocken

---

frontend/src/components/Layout/Layout.jsx
frontend/src/components/TeamModal/TeamModal.jsx
frontend/src/components/TeamModal/TeamModal.module.css
frontend/src/components/sections/Footer/Footer.jsx
frontend/src/data/teamMembers.js
frontend/src/index.css

feat(files): add team model

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/AddRecipeForm/AddRecipeForm.module.css
frontend/src/components/IngredientSelector/IngredientSelector.jsx
frontend/src/components/IngredientSelector/IngredientSelector.module.css
frontend/src/components/ui/RecipeTitleInput/RecipeTitleInput.module.css

feat: add error validation to ingredient selector component

---

frontend/src/components/AddRecipeForm/AddRecipeForm.jsx
frontend/src/components/MobileMenu/MobileMenu.module.css
frontend/src/components/Navigation/Navigation.module.css
frontend/src/components/RecipePreview/RecipePreview.module.css
frontend/src/components/TabsList/TabsList.module.css
frontend/src/components/UserInfo/UserInfo.module.css
frontend/src/components/UserProfile/UserProfile.module.css
frontend/src/components/sections/Categories/Categories.module.css
frontend/src/components/sections/Header/Header.module.css
frontend/src/components/sections/Hero/Hero.module.css
frontend/src/components/ui/UserAvatar/UserAvatar.jsx
frontend/src/components/ui/UserAvatar/UserAvatar.module.css
frontend/src/index.css
frontend/src/pages/AddRecipe/AddRecipePage.jsx
frontend/src/pages/Profile/Profile.jsx
frontend/src/pages/Profile/Profile.module.css

fix: style

---

frontend/src/components/CategoryCard/CategoryCard.jsx
frontend/src/components/CategoryCard/CategoryCard.module.css
frontend/src/components/CategoryList/CategoryList.jsx
frontend/src/components/CategoryList/CategoryList.module.css

categories refactoring

---

frontend/src/components/RecipeInfo/RecipeInfo.jsx

fix img recipe

---

frontend/src/components/ui/RecipeCard/RecipeCard.jsx
frontend/src/components/ui/RecipeCard/RecipeCard.module.css

fix(files): change styles

---

frontend/src/components/RecipeCardContainer/RecipeCardContainer.jsx
frontend/src/components/sections/Hero/Hero.jsx

feat(jsx): add animation to hero

---

frontend/index.html
frontend/src/components/sections/Footer/Footer.module.css
frontend/src/redux/recipes/recipesSlice.js

fix: fixes requested by mentor

---

frontend/src/components/ui/DropdownSelector/DropdownSelector.jsx
frontend/src/components/ui/DropdownSelector/DropdownSelector.module.css

feat: Add reset button to DropdownSelector
